# Generated by Django 3.2.6 on 2021-09-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descriptiion',
            new_name='description',
        ),
    ]
